# Generated by Django 4.0.5 on 2022-09-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('eid', 'uid')},
        ),
    ]
