# Generated by Django 4.0.5 on 2022-09-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkup', '0002_event_description_event_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='latitide',
            new_name='latitude',
        ),
    ]
