# Generated by Django 4.0.5 on 2022-09-04 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkup', '0002_alter_registration_end_alter_registration_start_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
    ]
