# Generated by Django 4.0.5 on 2022-09-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkup', '0003_alter_registration_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
